# Generated by Django 2.2.3 on 2019-12-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
